spring:
  application:
    name: bot
  datasource:
    url: jdbc:mysql://localhost:3306/bot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 0

server:
  port: 9901


